# Generated by Django 4.0.2 on 2022-02-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_twetter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sparkpredict',
            table='spark_twitter',
        ),
        migrations.AlterModelTable(
            name='twitter',
            table='twitter',
        ),
    ]
