# Generated by Django 4.0.2 on 2022-02-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_twetter', '0004_rename_predicton_sparkpredict_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparkpredict',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sparkpredict',
            name='location',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='sparkpredict',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sparkpredict',
            name='text',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='sparkpredict',
            name='time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
