# Generated by Django 4.0.2 on 2022-02-13 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_twetter', '0005_alter_sparkpredict_date_alter_sparkpredict_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sparkpredict',
            old_name='text',
            new_name='tweet',
        ),
        migrations.RenameField(
            model_name='twitter',
            old_name='text',
            new_name='tweet',
        ),
    ]
