# Generated by Django 4.0.2 on 2022-02-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_twetter', '0006_rename_text_sparkpredict_tweet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparkpredict',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
