# Generated by Django 4.0.2 on 2022-02-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_twetter', '0007_alter_sparkpredict_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparkpredict',
            name='time',
        ),
        migrations.RemoveField(
            model_name='twitter',
            name='time',
        ),
        migrations.AlterField(
            model_name='sparkpredict',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
