# Generated by Django 4.0.2 on 2022-02-13 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_twetter', '0008_remove_sparkpredict_time_remove_twitter_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('country', models.CharField(blank=True, max_length=70, null=True)),
                ('state', models.CharField(blank=True, max_length=70, null=True)),
                ('city', models.CharField(blank=True, max_length=70, null=True)),
                ('place_id', models.IntegerField(blank=True, null=True)),
                ('spark_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_twetter.sparkpredict')),
            ],
            options={
                'db_table': 'twitter_location',
            },
        ),
        migrations.DeleteModel(
            name='Twitter',
        ),
    ]
