# Generated by Django 4.0.2 on 2022-02-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_twetter', '0009_locale_delete_twitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locale',
            name='point',
        ),
        migrations.AddField(
            model_name='locale',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='locale',
            name='lon',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
