# Generated by Django 4.0.2 on 2022-02-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_twetter', '0010_remove_locale_point_locale_lat_locale_lon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sparkpredict',
            options={'ordering': ['date']},
        ),
    ]
