# Generated by Django 4.0.2 on 2022-02-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_twetter', '0011_alter_sparkpredict_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='locale',
            name='sigla',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
