# Generated by Django 4.0.2 on 2022-03-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_twetter', '0012_locale_sigla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locale',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='locale',
            name='lon',
        ),
        migrations.AlterField(
            model_name='sparkpredict',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
