# Generated by Django 4.0.2 on 2022-03-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_twetter', '0013_remove_locale_lat_remove_locale_lon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparkpredict',
            name='location',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
